### ISSUE TITLE
Add back button to the projects page

### ISSUE THREAD

**Issue by StrongSand94191** [Meta0Music/hhh-swart#14]
There's no back button on the projects page that goes back to the home page and it annoys me

**Comment by BaliDoggo** [comment]
Good idea I’ll try and do that today

**Comment by BaliDoggo** [comment]
i did it but also how do you see a preview of what the project would look like

**Comment by StrongSand94191** [comment]
i usually just either test in production like a gigachad or use inspect tool

**Comment by BaliDoggo** [comment]
ok

**Comment by StrongSand94191** [comment]
Deployed it, it looks nice tbh
